services:
  - type: web
    name: arieckal-erp
    runtime: node
    buildCommand: "cd frontend && npm install && npm run build"
    startCommand: "cd frontend && npm run preview"
    envVars:
      - key: NODE_ENV
        value: production
    staticPublishPath: frontend/dist
